### ISSUE TITLE
Stored Procedure Restore Fails from Generated SQL

### ISSUE THREAD

**Issue by adamfriedland** [MySqlBackupNET/MySqlBackup.Net#30]
Generated a SQL file containing a stored procedure using the `ExportToFile` function and then have tried to consume it using `ImportFromFile` which seems to resulting in a fail due `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line #`.

From what I've seen it seems to be related to the delimiter that I'm currently using. Is there a possible workaround for this?

**Comment by adriancs2** [comment]
Not enough info to identify the problem, try provide more details.

**Comment by Gus-van-Diermen** [comment]
I get this error with Triggers. In the backup,sql it has:

-- 
-- Dumping triggers
-- 

DROP TRIGGER /*!50030 IF EXISTS */ `team_member_AINS`;
DELIMITER |
CREATE TRIGGER `team_member_AINS` AFTER INSERT ON `team_member` FOR EACH ROW
INSERT INTO team_member_status_history VALUES (UUID(), NEW.Manager_code, NEW.Status, now()) |
DELIMITER ;

DROP TRIGGER /*!50030 IF EXISTS */ `team_member_BUPD`;
DELIMITER |
CREATE TRIGGER `team_member_BUPD` BEFORE UPDATE ON `team_member` FOR EACH ROW
BEGIN
	IF NOT NEW.Status <=> OLD.Status THEN
		INSERT INTO team_member_status_history VALUES (UUID(), NEW.Manager_code, NEW.Status, now());
	END IF;
END |
DELIMITER ;

gets the errors as follows:



MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '|' at line 2
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at MySql.Data.MySqlClient.MySqlScript.Execute()
   at MySql.Data.MySqlClient.MySqlBackup.Import_Routines()

MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 4
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at MySql.Data.MySqlClient.MySqlScript.Execute()
   at MySql.Data.MySqlClient.MySqlBackup.Import_Routines()
