### ISSUE TITLE
MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax

### ISSUE THREAD

**Issue by Gus-van-Diermen** [MySqlBackupNET/MySqlBackup.Net#36]
I get this error with Triggers. In the backup,sql it has:

--
-- Dumping triggers
DROP TRIGGER /*!50030 IF EXISTS */ team_member_AINS;
DELIMITER |
CREATE TRIGGER team_member_AINS AFTER INSERT ON team_member FOR EACH ROW
INSERT INTO team_member_status_history VALUES (UUID(), NEW.Manager_code, NEW.Status, now()) |
DELIMITER ;

DROP TRIGGER /*!50030 IF EXISTS */ team_member_BUPD;
DELIMITER |
CREATE TRIGGER team_member_BUPD BEFORE UPDATE ON team_member FOR EACH ROW
BEGIN
IF NOT NEW.Status <=> OLD.Status THEN
INSERT INTO team_member_status_history VALUES (UUID(), NEW.Manager_code, NEW.Status, now());
END IF;
END |
DELIMITER ;

gets the errors as follows:

MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '|' at line 2
at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
at MySql.Data.MySqlClient.MySqlScript.Execute()
at MySql.Data.MySqlClient.MySqlBackup.Import_Routines()

MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 4
at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
at MySql.Data.MySqlClient.MySqlScript.Execute()
at MySql.Data.MySqlClient.MySqlBackup.Import_Routines()

Also get this for functions and procedures though for me that is not a concern currently.

**Comment by gauravnewton** [comment]
Send the the complete problem i want to have a look

**Comment by adriancs2** [comment]
Let's join the discussion at the following issue:
https://github.com/MySqlBackupNET/MySqlBackup.Net/issues/38
I believe both discussion have the same problem.

**Comment by adriancs2** [comment]
This error is newly created in the last release which I have forget to handle the changes of the Delimiters.
I have dropped the support for handling the dependencies of Function, Procedure, Trigger and Events.
You may try the new release v2.2

**Comment by adriancs2** [comment]
Hi, a new version (v2.3) is released, where this problem is resolved. You may try it out.
